### ISSUE TITLE
Lots of incomplete text, wrong information in the corpus.  

### ISSUE THREAD

**Issue by djokester** [RatulGhosh/bengali_text_wikisource#2]
* Shakuntala was written in Bengali by Abanindranath Tagore and not Rabindranath Tagore. 
* The Text provided is very incomplete and doesn't have any continuity. 
* Feature Suggestion: Standard Scraper to scrape text off the Bengali WikiSource website.

**Comment by kylepjohnson** [comment]
@djokester Thank you for this. I am in need of your help. What do you recommend we do?

**Comment by djokester** [comment]
@kylepjohnson I am working on it. You can assign this to me.
I have already written down a few scrapers and expanded the data base.
